CREATE TABLE file (
	id SERIAL PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
	mime_type VARCHAR(100),
	file_key VARCHAR(255) NOT NULL,
	url TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);